export type KeywordBuckets = {
  trend: string[];
  art: string[];
  politics: string[];
  finance: string[];
};

export const keywords: KeywordBuckets = {
  "trend": [
    "ai",
    "artificial intelligence",
    "machine learning",
    "ml",
    "llm",
    "agent",
    "agentic",
    "model",
    "openai",
    "anthropic",
    "google",
    "microsoft",
    "meta",
    "nvidia",
    "ollama",
    "gpt-5",
    "claude 4",
    "llama 4",
    "gemini 3",
    "grok",
    "deepseek",
    "cloud",
    "developer",
    "cybersecurity",
    "security",
    "vulnerability",
    "gpu",
    "inference",
    "api",
    "rlvr",
    "autonomous",
    "react",
    "next.js",
    "nextjs",
    "frontend",
    "typescript",
    "javascript",
    "tailwind",
    "node",
    "vercel",
    "web dev",
    "architecture",
    "devops",
    "enterprise",
    "infrastructure",
    "database",
    "scaling",
    "saas",
    "serverless",
    "trends"
  ],
  "art": [
    "design",
    "ux",
    "ui",
    "visual",
    "illustration",
    "typography",
    "creative",
    "art"
  ],
  "politics": [
    "election",
    "president",
    "minister",
    "parliament",
    "senate",
    "government",
    "congress",
    "geopolitics",
    "war",
    "conflict",
    "diplomatic",
    "sanction",
    "policy debate",
    "campaign",
    "voting"
  ],
  "finance": [
    "oil market",
    "crude oil",
    "brent",
    "wti",
    "stock market",
    "exchange rate",
    "inflation",
    "commodity",
    "barrel",
    "gas price",
    "mortgage",
    "interest rate"
  ]
};
